#!/usr/bin/env ruby
#Load Logging
require 'lib/logger.rb'
#Create Log
log=Logger.new("log")

#Load Dependancies
log.log "Loading Requirements"
require 'lib/irc.rb'

#Create IRC Connection
log.log "Creating IRC Class"
irc=IRC.new

#Close the Log
log.close
